spring:
  application:
    name: kafka

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: externalized-demo
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
